/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    publications: Publication;
    news: News;
    'research-members': ResearchMember;
    'management-team': ManagementTeam;
    'research-line-content': ResearchLineContent;
    'policy-documents': PolicyDocument;
    'document-files': DocumentFile;
    'contact-messages': ContactMessage;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'research-members': ResearchMembersSelect<false> | ResearchMembersSelect<true>;
    'management-team': ManagementTeamSelect<false> | ManagementTeamSelect<true>;
    'research-line-content': ResearchLineContentSelect<false> | ResearchLineContentSelect<true>;
    'policy-documents': PolicyDocumentsSelect<false> | PolicyDocumentsSelect<true>;
    'document-files': DocumentFilesSelect<false> | DocumentFilesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    home: Home;
    about: About;
    governance: Governance;
    collaborations: Collaboration;
    transfer: Transfer;
    events: Event;
    initiatives: Initiative;
    communications: Communication;
    contact: Contact;
    services: Service;
    'public-policy': PublicPolicy;
    'publications-page': PublicationsPage;
    'news-page': NewsPage;
    'research-index': ResearchIndex;
    'management-page': ManagementPage;
    'mission-vision': MissionVision;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    governance: GovernanceSelect<false> | GovernanceSelect<true>;
    collaborations: CollaborationsSelect<false> | CollaborationsSelect<true>;
    transfer: TransferSelect<false> | TransferSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    initiatives: InitiativesSelect<false> | InitiativesSelect<true>;
    communications: CommunicationsSelect<false> | CommunicationsSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'public-policy': PublicPolicySelect<false> | PublicPolicySelect<true>;
    'publications-page': PublicationsPageSelect<false> | PublicationsPageSelect<true>;
    'news-page': NewsPageSelect<false> | NewsPageSelect<true>;
    'research-index': ResearchIndexSelect<false> | ResearchIndexSelect<true>;
    'management-page': ManagementPageSelect<false> | ManagementPageSelect<true>;
    'mission-vision': MissionVisionSelect<false> | MissionVisionSelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  /**
   * Identificador de la URL. Se genera automáticamente desde el título si se deja vacío.
   */
  slug: string;
  year: number;
  date: string;
  line:
    | 'nuevas-vacunas-para-peces'
    | 'enfermedades-y-resistencia-antimicrobiana'
    | 'soluciones-omicas'
    | 'estres-y-bienestar-animal'
    | 'impactos-en-ecosistemas'
    | 'resiliencia-de-la-acuicultura'
    | 'interacciones-sustentables'
    | 'impactos-socioeconomicos';
  authors: string;
  journal: string;
  /**
   * Si no hay contenido interno, la tarjeta enlaza directamente aquí.
   */
  url?: string | null;
  image?: (number | null) | Media;
  /**
   * Síntesis para la tarjeta y metadatos. Distinto por idioma.
   */
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descripción de la imagen para accesibilidad y SEO. Vacío solo si es puramente decorativa.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Identificador de la URL. Se genera automáticamente desde el título si se deja vacío.
   */
  slug: string;
  date: string;
  image: number | Media;
  imageAlt?: string | null;
  sourceUrl?: string | null;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-members".
 */
export interface ResearchMember {
  id: number;
  /**
   * Con título académico, tal como debe verse: “Dra. Ana Pérez”.
   */
  name: string;
  /**
   * Identificador de la URL. Se genera automáticamente desde el título si se deja vacío.
   */
  slug: string;
  line:
    | 'nuevas-vacunas-para-peces'
    | 'enfermedades-y-resistencia-antimicrobiana'
    | 'soluciones-omicas'
    | 'estres-y-bienestar-animal'
    | 'impactos-en-ecosistemas'
    | 'resiliencia-de-la-acuicultura'
    | 'interacciones-sustentables'
    | 'impactos-socioeconomicos';
  /**
   * Menor número, antes en la grilla. INCAR² define el orden por jerarquía (PI primero), no alfabético.
   */
  order: number;
  role: string;
  email?: string | null;
  /**
   * Retrato vertical. Si se deja vacío se muestra el isotipo de INCAR² en su lugar.
   */
  photo?: (number | null) | Media;
  /**
   * Perfiles externos. Dejar vacío el que la persona no tenga.
   */
  links?: {
    linkedin?: string | null;
    orcid?: string | null;
    scholar?: string | null;
    researchgate?: string | null;
  };
  /**
   * Separar los párrafos con una línea en blanco. Si queda vacía, la sección no aparece en el perfil.
   */
  bio?: string | null;
  /**
   * Un ítem por título, del más reciente al más antiguo.
   */
  degrees?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Un ítem por proyecto. Si la persona tiene muchos, cargar los más relevantes.
   */
  projects?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "management-team".
 */
export interface ManagementTeam {
  id: number;
  name: string;
  /**
   * Identificador de la URL. Se genera automáticamente desde el título si se deja vacío.
   */
  slug: string;
  team: 'direction' | 'executive';
  order: number;
  /**
   * Solo si la persona también integra una línea: identificador de su ficha de investigador. La tarjeta enlazará ahí en vez de crear un perfil aparte.
   */
  memberSlug?: string | null;
  role: string;
  email?: string | null;
  /**
   * Retrato vertical. Si se deja vacío se muestra el isotipo de INCAR² en su lugar.
   */
  photo?: (number | null) | Media;
  /**
   * Perfiles externos. Dejar vacío el que la persona no tenga.
   */
  links?: {
    linkedin?: string | null;
    orcid?: string | null;
    scholar?: string | null;
    researchgate?: string | null;
  };
  /**
   * Separar los párrafos con una línea en blanco. Si queda vacía, la sección no aparece en el perfil.
   */
  bio?: string | null;
  /**
   * Un ítem por título, del más reciente al más antiguo.
   */
  degrees?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Un ítem por proyecto. Si la persona tiene muchos, cargar los más relevantes.
   */
  projects?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Textos de cada línea. Lo que se deje vacío conserva el texto actual del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-line-content".
 */
export interface ResearchLineContent {
  id: number;
  /**
   * Cada línea puede tener una sola ficha de textos.
   */
  line:
    | 'nuevas-vacunas-para-peces'
    | 'enfermedades-y-resistencia-antimicrobiana'
    | 'soluciones-omicas'
    | 'estres-y-bienestar-animal'
    | 'impactos-en-ecosistemas'
    | 'resiliencia-de-la-acuicultura'
    | 'interacciones-sustentables'
    | 'impactos-socioeconomicos';
  /**
   * Se completa solo a partir de la línea seleccionada.
   */
  adminTitle?: string | null;
  eyebrow?: string | null;
  title?: string | null;
  /**
   * Solo la usa RL1, cuyo título se parte en dos colores. Dejar vacío en las demás.
   */
  titleAccent?: string | null;
  lead?: string | null;
  heroCta?: string | null;
  focusEyebrow?: string | null;
  focusText?: string | null;
  objEyebrow?: string | null;
  objTitle?: string | null;
  objectives?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  transferEyebrow?: string | null;
  transferTitle?: string | null;
  transferText?: string | null;
  transferItems?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  closingEyebrow?: string | null;
  closingTitle?: string | null;
  closingTitleAccent?: string | null;
  closingText?: string | null;
  closingCta?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Policy Briefs, asesorías parlamentarias y otros documentos de la página Políticas Públicas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-documents".
 */
export interface PolicyDocument {
  id: number;
  /**
   * Define en qué pestaña aparece.
   */
  kind: 'policy-brief' | 'advisory' | 'other';
  /**
   * Correlativo que se muestra en la tarjeta. Los “otros documentos” no lo usan.
   */
  number?: number | null;
  /**
   * Verbatim, tal como lo entregó INCAR².
   */
  title: string;
  /**
   * Texto libre, como “Octubre 2020”. Solo lo usan los otros documentos.
   */
  date?: string | null;
  /**
   * Solo la muestran los otros documentos.
   */
  description?: string | null;
  file: number | DocumentFile;
  /**
   * Opcional. Añade un segundo botón de descarga en la tarjeta.
   */
  summaryFile?: (number | null) | DocumentFile;
  /**
   * Archivos adicionales que acompañan al documento.
   */
  annexes?:
    | {
        label: string;
        file: number | DocumentFile;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Biblioteca de PDF. Se enlazan desde las fichas de documentos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-files".
 */
export interface DocumentFile {
  id: number;
  /**
   * Referencia interna para encontrarlo. No se muestra en el sitio.
   */
  label?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Mensajes recibidos desde el formulario de la página de Contacto. Marca «Atendido» cuando ya se respondió.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  city?: string | null;
  country?: string | null;
  message: string;
  /**
   * Marca esta casilla cuando el mensaje ya fue respondido.
   */
  handled?: boolean | null;
  /**
   * Idioma en que se envió el formulario; úsalo para responder.
   */
  locale?: ('es' | 'en') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editor: crea y publica Noticias, Publicaciones y Medios. Administrador: además gestiona las cuentas de usuario.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'research-members';
        value: number | ResearchMember;
      } | null)
    | ({
        relationTo: 'management-team';
        value: number | ManagementTeam;
      } | null)
    | ({
        relationTo: 'research-line-content';
        value: number | ResearchLineContent;
      } | null)
    | ({
        relationTo: 'policy-documents';
        value: number | PolicyDocument;
      } | null)
    | ({
        relationTo: 'document-files';
        value: number | DocumentFile;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  year?: T;
  date?: T;
  line?: T;
  authors?: T;
  journal?: T;
  url?: T;
  image?: T;
  summary?: T;
  content?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  image?: T;
  imageAlt?: T;
  sourceUrl?: T;
  excerpt?: T;
  content?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-members_select".
 */
export interface ResearchMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  line?: T;
  order?: T;
  role?: T;
  email?: T;
  photo?: T;
  links?:
    | T
    | {
        linkedin?: T;
        orcid?: T;
        scholar?: T;
        researchgate?: T;
      };
  bio?: T;
  degrees?:
    | T
    | {
        value?: T;
        id?: T;
      };
  projects?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "management-team_select".
 */
export interface ManagementTeamSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  team?: T;
  order?: T;
  memberSlug?: T;
  role?: T;
  email?: T;
  photo?: T;
  links?:
    | T
    | {
        linkedin?: T;
        orcid?: T;
        scholar?: T;
        researchgate?: T;
      };
  bio?: T;
  degrees?:
    | T
    | {
        value?: T;
        id?: T;
      };
  projects?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-line-content_select".
 */
export interface ResearchLineContentSelect<T extends boolean = true> {
  line?: T;
  adminTitle?: T;
  eyebrow?: T;
  title?: T;
  titleAccent?: T;
  lead?: T;
  heroCta?: T;
  focusEyebrow?: T;
  focusText?: T;
  objEyebrow?: T;
  objTitle?: T;
  objectives?:
    | T
    | {
        value?: T;
        id?: T;
      };
  transferEyebrow?: T;
  transferTitle?: T;
  transferText?: T;
  transferItems?:
    | T
    | {
        value?: T;
        id?: T;
      };
  closingEyebrow?: T;
  closingTitle?: T;
  closingTitleAccent?: T;
  closingText?: T;
  closingCta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-documents_select".
 */
export interface PolicyDocumentsSelect<T extends boolean = true> {
  kind?: T;
  number?: T;
  title?: T;
  date?: T;
  description?: T;
  file?: T;
  summaryFile?: T;
  annexes?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-files_select".
 */
export interface DocumentFilesSelect<T extends boolean = true> {
  label?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  city?: T;
  country?: T;
  message?: T;
  handled?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Textos de la portada. Lo que se deje vacío conserva el texto actual del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroTitle?: string | null;
  /**
   * Se muestra en color teal, a continuación del título.
   */
  heroTitleAccent?: string | null;
  heroSubtitle?: string | null;
  heroCta1?: string | null;
  heroCta2?: string | null;
  quickTour?: string | null;
  quickNetworks?: string | null;
  quickNews?: string | null;
  quickDocuments?: string | null;
  quickPolicy?: string | null;
  quickEvents?: string | null;
  slideSrsTitle?: string | null;
  slideSrsText?: string | null;
  slideSrsAlt?: string | null;
  slideEpimarTitle?: string | null;
  slideEpimarText?: string | null;
  slideEpimarAlt?: string | null;
  slidePolicyTitle?: string | null;
  slidePolicyText?: string | null;
  slidePolicyCta?: string | null;
  slideInitiativesTitle?: string | null;
  slideInitiativesText?: string | null;
  slideInitiativesCta?: string | null;
  slideMoreInfo?: string | null;
  researchEyebrow?: string | null;
  researchTitle?: string | null;
  researchText?: string | null;
  researchCta?: string | null;
  researchImageAlt?: string | null;
  stEyebrow?: string | null;
  stTitle?: string | null;
  stText?: string | null;
  stImageAlt?: string | null;
  stWhatIs?: string | null;
  stSferaFull?: string | null;
  stSferaText?: string | null;
  stInahFull?: string | null;
  stInahText?: string | null;
  stSummaryTitle?: string | null;
  stSummary?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  stCtaServices?: string | null;
  stCtaTransfer?: string | null;
  collaborationEyebrow?: string | null;
  collaborationTitle?: string | null;
  collabLabel?: string | null;
  collabText?: string | null;
  socialEyebrow?: string | null;
  socialTitle?: string | null;
  socialText?: string | null;
  sponsorTitle?: string | null;
  associatedTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos de la página Quiénes Somos. Lo que se deje vacío conserva el texto actual del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  eyebrow?: string | null;
  historyTitle?: string | null;
  history1?: string | null;
  title2?: string | null;
  text2?: string | null;
  title3?: string | null;
  /**
   * La sección se muestra en 2 o 3 columnas según la cantidad de párrafos.
   */
  historyParagraphs?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  boxTitle?: string | null;
  text4?: string | null;
  institutionsText?: string | null;
  cta?: string | null;
  teamImageAlt?: string | null;
  missionTitle?: string | null;
  missionText?: string | null;
  visionTitle?: string | null;
  visionText?: string | null;
  objGeneralTitle?: string | null;
  objGeneralText?: string | null;
  objTitle?: string | null;
  objectives?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos de la página Gobernanza. Lo que se deje vacío conserva el texto actual del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "governance".
 */
export interface Governance {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  councilEyebrow?: string | null;
  councilTitle?: string | null;
  councilText?: string | null;
  institutionsTitle?: string | null;
  institutionsText?: string | null;
  boardTitle?: string | null;
  boardText1?: string | null;
  boardText2?: string | null;
  alliancesEyebrow?: string | null;
  alliancesTitle?: string | null;
  alliancesText1?: string | null;
  alliancesText2?: string | null;
  advisoryTitle?: string | null;
  advisoryText1?: string | null;
  advisoryText2?: string | null;
  advisoryImageAlt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos de la página de colaboración nacional e internacional. Lo que se deje vacío conserva el texto actual.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collaborations".
 */
export interface Collaboration {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  lead?: string | null;
  nationalTitle?: string | null;
  nationalText?: string | null;
  internationalTitle?: string | null;
  internationalText?: string | null;
  mechanismsTitle?: string | null;
  mechanismsIntro?: string | null;
  /**
   * El título se destaca y la descripción lo completa en la misma línea.
   */
  mechanisms?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  ecosText?: string | null;
  internshipsText?: string | null;
  natihTitle?: string | null;
  natihText1?: string | null;
  natihText2?: string | null;
  logosEyebrow?: string | null;
  logosTitle?: string | null;
  groupSponsor?: string | null;
  groupNational?: string | null;
  groupAllies?: string | null;
  groupInternational?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos de la página de transferencia tecnológica. Lo que se deje vacío conserva el texto actual.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfer".
 */
export interface Transfer {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  missionText1?: string | null;
  missionText2?: string | null;
  programsEyebrow?: string | null;
  programsTitle?: string | null;
  whatIs?: string | null;
  sferaName?: string | null;
  sferaFull?: string | null;
  sferaText?: string | null;
  inahName?: string | null;
  inahFull?: string | null;
  inahText1?: string | null;
  inahText2?: string | null;
  inahText3?: string | null;
  synergyTitle?: string | null;
  synergyText1?: string | null;
  synergyText2?: string | null;
  objGeneralTitle?: string | null;
  objGeneralText?: string | null;
  objSpecificTitle?: string | null;
  objectives?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  contactText?: string | null;
  contactEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos de la página de eventos. Lo que se deje vacío conserva el texto actual del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  intro1?: string | null;
  intro2?: string | null;
  intro3?: string | null;
  listEyebrow?: string | null;
  visitSite?: string | null;
  srsName?: string | null;
  srsText1?: string | null;
  srsText2?: string | null;
  srsText3?: string | null;
  srsText4?: string | null;
  srsText5?: string | null;
  srsUrl?: string | null;
  epimarName?: string | null;
  epimarText1?: string | null;
  epimarText2?: string | null;
  epimarText3?: string | null;
  epimarDatesTitle?: string | null;
  epimarDates?: string | null;
  epimarUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos de la página de iniciativas. Lo que se deje vacío conserva el texto actual del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "initiatives".
 */
export interface Initiative {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  sectionLabel?: string | null;
  caligusTitle?: string | null;
  caligusText?: string | null;
  srsTitle?: string | null;
  srsText1?: string | null;
  srsText2?: string | null;
  restorativeTitle?: string | null;
  /**
   * Mensaje mientras la iniciativa esté en preparación.
   */
  restorativeNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos de la página de comunicaciones y vinculación. Lo que se deje vacío conserva el texto actual.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "communications".
 */
export interface Communication {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  lead?: string | null;
  heroCta?: string | null;
  disseminationEyebrow?: string | null;
  disseminationText?: string | null;
  disseminationImageAlt?: string | null;
  outreachEyebrow?: string | null;
  outreachTitle?: string | null;
  outreachText?: string | null;
  outreachImageAlt?: string | null;
  ecosystemEyebrow?: string | null;
  ecosystemTitle?: string | null;
  mapeoEyebrow?: string | null;
  mapeoTitle?: string | null;
  /**
   * Describe el contenido de la infografía para quien no puede verla. Conviene que sea detallado.
   */
  mapeoImageAlt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos de la página de contacto. Lo que se deje vacío conserva el texto actual del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  lead?: string | null;
  formTitle?: string | null;
  fieldName?: string | null;
  fieldEmail?: string | null;
  fieldPhone?: string | null;
  fieldCity?: string | null;
  fieldCountry?: string | null;
  fieldMessage?: string | null;
  submit?: string | null;
  /**
   * Explica que el envío todavía no está habilitado.
   */
  formNotice?: string | null;
  emailTitle?: string | null;
  email?: string | null;
  officesTitle?: string | null;
  phoneLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos de la página de servicios. Lo que se deje vacío conserva el texto actual del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  lead?: string | null;
  areaLabel?: string | null;
  servicesTitle?: string | null;
  futureTitle?: string | null;
  ctaTitle?: string | null;
  ctaText?: string | null;
  ctaEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos de la página de políticas públicas. Lo que se deje vacío conserva el texto actual.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-policy".
 */
export interface PublicPolicy {
  id: number;
  title?: string | null;
  heroTitle?: string | null;
  intro1?: string | null;
  intro2?: string | null;
  whyTitle?: string | null;
  whyLead?: string | null;
  axis1Title?: string | null;
  axis1Text?: string | null;
  axis2Title?: string | null;
  axis2Text?: string | null;
  axis3Title?: string | null;
  axis3Text?: string | null;
  listTitle?: string | null;
  tabPolicyBrief?: string | null;
  tabAdvisory?: string | null;
  tabOther?: string | null;
  briefLabel?: string | null;
  advisoryLabel?: string | null;
  otherDocLabel?: string | null;
  download?: string | null;
  downloadSummary?: string | null;
  advisoryTitle?: string | null;
  advisoryIntro1?: string | null;
  advisoryIntro2?: string | null;
  advisoryIntro3?: string | null;
  otherTitle?: string | null;
  otherIntro1?: string | null;
  otherIntro2?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Encabezado y etiquetas de la página de publicaciones. Los papers se administran en la colección Publicaciones.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications-page".
 */
export interface PublicationsPage {
  id: number;
  title?: string | null;
  lead?: string | null;
  leadSecondary?: string | null;
  searchPlaceholder?: string | null;
  filtersLabel?: string | null;
  allCategories?: string | null;
  filterByLine?: string | null;
  filterByYear?: string | null;
  clearFilters?: string | null;
  noResultsTitle?: string | null;
  noResultsText?: string | null;
  viewPublication?: string | null;
  originalArticle?: string | null;
  readMore?: string | null;
  backToList?: string | null;
  authorsLabel?: string | null;
  publishedIn?: string | null;
  categoryLabel?: string | null;
  relatedTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Encabezado y etiquetas de la página de noticias. Las notas se administran en la colección Noticias.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-page".
 */
export interface NewsPage {
  id: number;
  title?: string | null;
  lead?: string | null;
  readMore?: string | null;
  backToList?: string | null;
  relatedTitle?: string | null;
  sourceLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Encabezado de la página que lista las ocho líneas de investigación.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-index".
 */
export interface ResearchIndex {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  lead?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Encabezado de la página de equipo de gestión. Las personas se administran en la colección Equipo de gestión.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "management-page".
 */
export interface ManagementPage {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  lead?: string | null;
  directionTitle?: string | null;
  executiveTitle?: string | null;
  backToTeam?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Título de la página. Los textos de misión y visión están en Quiénes Somos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mission-vision".
 */
export interface MissionVision {
  id: number;
  title?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroTitle?: T;
  heroTitleAccent?: T;
  heroSubtitle?: T;
  heroCta1?: T;
  heroCta2?: T;
  quickTour?: T;
  quickNetworks?: T;
  quickNews?: T;
  quickDocuments?: T;
  quickPolicy?: T;
  quickEvents?: T;
  slideSrsTitle?: T;
  slideSrsText?: T;
  slideSrsAlt?: T;
  slideEpimarTitle?: T;
  slideEpimarText?: T;
  slideEpimarAlt?: T;
  slidePolicyTitle?: T;
  slidePolicyText?: T;
  slidePolicyCta?: T;
  slideInitiativesTitle?: T;
  slideInitiativesText?: T;
  slideInitiativesCta?: T;
  slideMoreInfo?: T;
  researchEyebrow?: T;
  researchTitle?: T;
  researchText?: T;
  researchCta?: T;
  researchImageAlt?: T;
  stEyebrow?: T;
  stTitle?: T;
  stText?: T;
  stImageAlt?: T;
  stWhatIs?: T;
  stSferaFull?: T;
  stSferaText?: T;
  stInahFull?: T;
  stInahText?: T;
  stSummaryTitle?: T;
  stSummary?:
    | T
    | {
        value?: T;
        id?: T;
      };
  stCtaServices?: T;
  stCtaTransfer?: T;
  collaborationEyebrow?: T;
  collaborationTitle?: T;
  collabLabel?: T;
  collabText?: T;
  socialEyebrow?: T;
  socialTitle?: T;
  socialText?: T;
  sponsorTitle?: T;
  associatedTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  eyebrow?: T;
  historyTitle?: T;
  history1?: T;
  title2?: T;
  text2?: T;
  title3?: T;
  historyParagraphs?:
    | T
    | {
        value?: T;
        id?: T;
      };
  boxTitle?: T;
  text4?: T;
  institutionsText?: T;
  cta?: T;
  teamImageAlt?: T;
  missionTitle?: T;
  missionText?: T;
  visionTitle?: T;
  visionText?: T;
  objGeneralTitle?: T;
  objGeneralText?: T;
  objTitle?: T;
  objectives?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "governance_select".
 */
export interface GovernanceSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  councilEyebrow?: T;
  councilTitle?: T;
  councilText?: T;
  institutionsTitle?: T;
  institutionsText?: T;
  boardTitle?: T;
  boardText1?: T;
  boardText2?: T;
  alliancesEyebrow?: T;
  alliancesTitle?: T;
  alliancesText1?: T;
  alliancesText2?: T;
  advisoryTitle?: T;
  advisoryText1?: T;
  advisoryText2?: T;
  advisoryImageAlt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collaborations_select".
 */
export interface CollaborationsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  nationalTitle?: T;
  nationalText?: T;
  internationalTitle?: T;
  internationalText?: T;
  mechanismsTitle?: T;
  mechanismsIntro?: T;
  mechanisms?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  ecosText?: T;
  internshipsText?: T;
  natihTitle?: T;
  natihText1?: T;
  natihText2?: T;
  logosEyebrow?: T;
  logosTitle?: T;
  groupSponsor?: T;
  groupNational?: T;
  groupAllies?: T;
  groupInternational?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfer_select".
 */
export interface TransferSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  missionText1?: T;
  missionText2?: T;
  programsEyebrow?: T;
  programsTitle?: T;
  whatIs?: T;
  sferaName?: T;
  sferaFull?: T;
  sferaText?: T;
  inahName?: T;
  inahFull?: T;
  inahText1?: T;
  inahText2?: T;
  inahText3?: T;
  synergyTitle?: T;
  synergyText1?: T;
  synergyText2?: T;
  objGeneralTitle?: T;
  objGeneralText?: T;
  objSpecificTitle?: T;
  objectives?:
    | T
    | {
        value?: T;
        id?: T;
      };
  contactText?: T;
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  intro1?: T;
  intro2?: T;
  intro3?: T;
  listEyebrow?: T;
  visitSite?: T;
  srsName?: T;
  srsText1?: T;
  srsText2?: T;
  srsText3?: T;
  srsText4?: T;
  srsText5?: T;
  srsUrl?: T;
  epimarName?: T;
  epimarText1?: T;
  epimarText2?: T;
  epimarText3?: T;
  epimarDatesTitle?: T;
  epimarDates?: T;
  epimarUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "initiatives_select".
 */
export interface InitiativesSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  sectionLabel?: T;
  caligusTitle?: T;
  caligusText?: T;
  srsTitle?: T;
  srsText1?: T;
  srsText2?: T;
  restorativeTitle?: T;
  restorativeNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "communications_select".
 */
export interface CommunicationsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  heroCta?: T;
  disseminationEyebrow?: T;
  disseminationText?: T;
  disseminationImageAlt?: T;
  outreachEyebrow?: T;
  outreachTitle?: T;
  outreachText?: T;
  outreachImageAlt?: T;
  ecosystemEyebrow?: T;
  ecosystemTitle?: T;
  mapeoEyebrow?: T;
  mapeoTitle?: T;
  mapeoImageAlt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  formTitle?: T;
  fieldName?: T;
  fieldEmail?: T;
  fieldPhone?: T;
  fieldCity?: T;
  fieldCountry?: T;
  fieldMessage?: T;
  submit?: T;
  formNotice?: T;
  emailTitle?: T;
  email?: T;
  officesTitle?: T;
  phoneLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  areaLabel?: T;
  servicesTitle?: T;
  futureTitle?: T;
  ctaTitle?: T;
  ctaText?: T;
  ctaEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-policy_select".
 */
export interface PublicPolicySelect<T extends boolean = true> {
  title?: T;
  heroTitle?: T;
  intro1?: T;
  intro2?: T;
  whyTitle?: T;
  whyLead?: T;
  axis1Title?: T;
  axis1Text?: T;
  axis2Title?: T;
  axis2Text?: T;
  axis3Title?: T;
  axis3Text?: T;
  listTitle?: T;
  tabPolicyBrief?: T;
  tabAdvisory?: T;
  tabOther?: T;
  briefLabel?: T;
  advisoryLabel?: T;
  otherDocLabel?: T;
  download?: T;
  downloadSummary?: T;
  advisoryTitle?: T;
  advisoryIntro1?: T;
  advisoryIntro2?: T;
  advisoryIntro3?: T;
  otherTitle?: T;
  otherIntro1?: T;
  otherIntro2?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications-page_select".
 */
export interface PublicationsPageSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  leadSecondary?: T;
  searchPlaceholder?: T;
  filtersLabel?: T;
  allCategories?: T;
  filterByLine?: T;
  filterByYear?: T;
  clearFilters?: T;
  noResultsTitle?: T;
  noResultsText?: T;
  viewPublication?: T;
  originalArticle?: T;
  readMore?: T;
  backToList?: T;
  authorsLabel?: T;
  publishedIn?: T;
  categoryLabel?: T;
  relatedTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-page_select".
 */
export interface NewsPageSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  readMore?: T;
  backToList?: T;
  relatedTitle?: T;
  sourceLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-index_select".
 */
export interface ResearchIndexSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "management-page_select".
 */
export interface ManagementPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  directionTitle?: T;
  executiveTitle?: T;
  backToTeam?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mission-vision_select".
 */
export interface MissionVisionSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}